package dev.blanky.vinyl.ui.theme

import androidx.compose.ui.graphics.Color

// Ciepła, "analogowa" paleta — grafit z bursztynowym akcentem.

val VinylBg = Color(0xFF121014)
val VinylSurface = Color(0xFF17141A)
val VinylSurfaceHigh = Color(0xFF2A2630)
val VinylPrimaryDark = Color(0xFFE8B04B)
val VinylOnPrimaryDark = Color(0xFF221602)
val VinylPrimaryContainerDark = Color(0xFF513A0F)
val VinylOnPrimaryContainerDark = Color(0xFFF5D793)
val VinylSecondaryDark = Color(0xFFC9A68B)
val VinylOnSecondaryDark = Color(0xFF33241A)
val VinylSecondaryContainerDark = Color(0xFF4A3A2E)
val VinylOnSecondaryContainerDark = Color(0xFFEAD6C6)
val VinylTertiaryDark = Color(0xFFBFA3B5)
val VinylOnTertiaryDark = Color(0xFF3B2836)
val VinylTertiaryContainerDark = Color(0xFF52404C)
val VinylOnTertiaryContainerDark = Color(0xFFE4CFD9)
val VinylOnSurfaceDark = Color(0xFFE9E2D8)
val VinylOnSurfaceVariantDark = Color(0xFFB0A698)
val VinylSurfaceVariantDark = Color(0xFF2A252E)
val VinylOutlineDark = Color(0xFF4A4350)
val VinylOutlineVariantDark = Color(0xFF322D38)
val VinylInverseSurfaceDark = Color(0xFFE0D8CE)
val VinylOnInverseSurfaceDark = Color(0xFF2F2A24)
val VinylErrorDark = Color(0xFFF2B8B5)
val VinylOnErrorDark = Color(0xFF690005)
val VinylErrorContainerDark = Color(0xFF93000A)
val VinylOnErrorContainerDark = Color(0xFFF9DEDC)
val VinylScrim = Color(0xFF000000)

val VinylSurfaceContainerLowest = Color(0xFF0F0D11)
val VinylSurfaceContainerLow = Color(0xFF1B181E)
val VinylSurfaceContainer = Color(0xFF1F1C22)
val VinylSurfaceContainerHigh = Color(0xFF2A2630)
val VinylSurfaceContainerHighest = Color(0xFF352F3B)

val VinylBgLight = Color(0xFFF7F2EA)
val VinylSurfaceLight = Color(0xFFFBF7F0)
val VinylPrimaryLight = Color(0xFF8A5A10)
val VinylOnPrimaryLight = Color(0xFFFFF8ED)
val VinylPrimaryContainerLight = Color(0xFFFFE0A8)
val VinylOnPrimaryContainerLight = Color(0xFF2C1B00)
val VinylSecondaryLight = Color(0xFF7A5A44)
val VinylOnSecondaryLight = Color(0xFFFFF9F4)
val VinylSecondaryContainerLight = Color(0xFFF4DCCE)
val VinylOnSecondaryContainerLight = Color(0xFF2D1D12)
val VinylTertiaryLight = Color(0xFF6E4B5E)
val VinylOnTertiaryLight = Color(0xFFFFF7FA)
val VinylTertiaryContainerLight = Color(0xFFF5DCE5)
val VinylOnTertiaryContainerLight = Color(0xFF28121C)
val VinylOnSurfaceLight = Color(0xFF221C14)
val VinylOnSurfaceVariantLight = Color(0xFF524842)
val VinylSurfaceVariantLight = Color(0xFFE7DDD2)
val VinylOutlineLight = Color(0xFF84796F)
val VinylOutlineVariantLight = Color(0xFFD0C4B7)
val VinylInverseSurfaceLight = Color(0xFF382F27)
val VinylOnInverseSurfaceLight = Color(0xFFF7EDE2)
val VinylErrorLight = Color(0xFFBA1A1A)
val VinylOnErrorLight = Color(0xFFFFFFFF)
val VinylErrorContainerLight = Color(0xFFFFDAD6)
val VinylOnErrorContainerLight = Color(0xFF410002)

val VinylSurfaceContainerLowestLight = Color(0xFFFFFBF4)
val VinylSurfaceContainerLowLight = Color(0xFFFAF5EC)
val VinylSurfaceContainerLight = Color(0xFFF4EDE3)
val VinylSurfaceContainerHighLight = Color(0xFFEEE5DA)
val VinylSurfaceContainerHighestLight = Color(0xFFE8DED3)
